### ISSUE TITLE
load-data script 

### ISSUE THREAD

**Issue by dominikwozniak** [Project-Summer-AI-Lab-Glider/process-mining#1]
Skrypt służący do pobierania maili z [link](http://mail-archives.apache.org/mod_mbox/camel-dev/201704.mbox/browser). Za pomocą odpowiednich flag będzie możliwe umieszcaanie maili w podfolderach grupujących dane maile według podanej etykiety.

Edit @Valaraucoo : 
* pobieranie danych do np. .csv,
* dodac logi informujace o powodzeniu / niepowodzeniu,
* zapis w wybranych folderze (mozna to ustawiac / domyslnie np. folder `data/`),
* zadbac o odpowiednie labele  ,
* moze dac mozliwosc zapisu wybranego formatu (?).

**Comment by Valaraucoo** [comment]
* Pobrać Camel User List, Camel Developer List, Camel Commits List, Camel Issues List z https://camel.apache.org/manual/latest/mailing-lists.html 

* przefiltorwane dla daty od 14/04/2017 do 19/04/2017
